stages:
  - lint
  - test
  - deploy

image: node:14.16.1

cache:
  - key:
      files:
        - yarn.lock
    paths:
      - .yarn-cache/
  - key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .jest-cache

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - yarn install --cache-folder .yarn-cache

lint:
  stage: lint
  except:
    changes:
      - "*.md"
  script:
    - yarn lint

tests:unit:
  stage: test
  except:
    changes:
      - "*.md"
  script:
    - yarn ci:test:coverage
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
#
# tests:e2e:
#   stage: test
#   only:
#     - master
#   script:
#     - yarn ci:test:e2e

expo-deployments:
  stage: deploy
  only:
    - master
  script:
    - apk add --no-cache bash
    - npm install --save-dev expo-cli
    - expo login --non-interactive -u $EXPO_USERNAME
    - expo whoami
    - expo publish --non-interactive --target managed --release-channel development
