stages:
  - test
  - deploy

image: node:14.16.1

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .jest
    - .yarn

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - yarn add global expo-cli
  - yarn install --cache-folder .yarn

lint:
  stage: test
  except:
    changes:
      - "*.md"
  script:
    - yarn lint

tests:unit:
  stage: test
  except:
    changes:
      - "*.md"
  script:
    - yarn ci:test:coverage
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
#
# tests:e2e:
#   stage: test
#   only:
#     - master
#   script:
#     - yarn ci:test:e2e

deploy:
  stage: deploy
  only:
    - master
  script:
    - yarn add expo-cli
    - expo login --non-interactive -u $EXPO_USERNAME
    - expo whoami
    - expo publish --non-interactive --target managed --release-channel development
